## Numpy Exercise Questions


- Create a New environment and install numpy in it
- Check the version of numpy using pip freeze and __version__

In [3]:
pip install numpy

Given are 2 similar dimensional numpy arrays perform element wise addition


\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}



\begin{bmatrix}
10 & 11 & 12 \\
13 & 14 & 15 \\
\end{bmatrix}


In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11,12],[13,14,15]])
c = a+b
print(c)

[[11 13 15]
 [17 19 21]]


Multiply the following matrix with a scalar 2


\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}


In [5]:
a = np.array([[1,2,3], [4,5,6]])
b = np.multiply(a,2)
print(b)

[[ 2  4  6]
 [ 8 10 12]]


Create a identiy matrix of 4X4
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}

In [6]:
a = np.eye(4, dtype = np.int64)
print(a)
print(a.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
int64


Construct a 1D array and reshape to 3D array 3X3X3 shape



In [7]:
array_1D = np.arange(0,27)                    # Create 1D array value from 0-26
array_3D = array_1D.reshape(3, 3, 3)        # Reshaping the 1D array to 3D in 3x3x3
print(array_3D)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Convert all the elements of a numpy array from float to integer datatype. Hint: use `astype`

\begin{bmatrix}
2.5 & 3.8 & 1.5 \\
4.7 & 2.9 & 1.56
\end{bmatrix}

In [8]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])
print(a, "\t" "Data type of a:", a.dtype)
new_a = a.astype(int)
print(new_a, "\t" "Data type of new_a:", new_a.dtype)

[[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]] 	Data type of a: float64
[[2 3 1]
 [4 2 1]] 	Data type of new_a: int64


Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array: i.e. to True, False

\begin{bmatrix}
1 & 0 & 0 \\
1 & 1 & 1 \\
0 & 0 & 0
\end{bmatrix}

In [9]:
original_array = np.array([[1,0,0], [ 0,1,0], [0,0,1]])
print(f"Original array:\n {original_array}")
boolian_a = original_array.astype(bool)
print(f"Bool array:\n {boolian_a}")

Original array:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Bool array:
 [[ True False False]
 [False  True False]
 [False False  True]]


Horizontally stack the following matrix

\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}

\begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}

In [10]:
arr_1=np.array([[1,2,3],[4,5,6]])
arr_2=np.array([[7,8,9],[10, 11, 12]])

new_arr =np.hstack((arr_1,arr_2))
print(new_arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers: Hint use `np.arange`

output: `[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]`

In [11]:
ran_arr = np.arange(0,102,2)
print(ran_arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Write a NumPy program that creates a large 1D array using `np.random.rand` and write a function to calculate the sum of its elements using a for loop. Then, optimize it using NumPy's built-in functions.

In [12]:
#using loop here

random_number = np.random.rand(1000000)
sum = 0
for number in random_number:
    sum += number
print(f"Sum of random numnber using loop:\t{sum}")


Sum of random numnber using loop:	500026.38991437305


In [13]:
# using numpy here

print(f"Sum of random using numpy:\t{np.sum(random_number)}")

Sum of random using numpy:	500026.3899143637


From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match
`[1,2,3,4,5]` and `[1,3,2,4,5]`


In [14]:
# Hint: use 'np.where'

In [15]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([1,3,2,4,5])

matching_index = np.where(arr_1==arr_2)
print(matching_index)

(array([0, 3, 4]),)


Output a sequence of equally gapped 5 numbers in the range 0 to 100
Output: `[  0.  25.  50.  75. 100.]`

In [16]:
# Hint: use np.linspace

In [17]:
gapped_num =np.linspace(0,100,5)
print(gapped_num)

[  0.  25.  50.  75. 100.]


Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

\begin{bmatrix}
5 & 5 & 5 \\
5 & 5 & 5
\end{bmatrix}

In [18]:
arr = np.full((2,3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


Output a 5-by-5 array of random integers between 0 and 10



In [19]:
arr = np.random.randint(0,11,(5,5))
print(arr)

[[ 0  0  1 10  1]
 [ 4  8  5  5  3]
 [ 8  4  3  9  7]
 [ 2  4  5  6  4]
 [ 5  2  0 10  5]]


Dot Product:
\begin{bmatrix}
1 & 2 \\
2 & 3
\end{bmatrix}

\begin{bmatrix}
4 & 5 \\
6 & 7
\end{bmatrix}

Dot product is:
\begin{bmatrix}
1 \times 4 + 2 \times 6 & 2 \times 4 + 3 \times 6 \\
1 \times 5 + 2 \times 7 & 2 \times 5 + 3 \times 7
\end{bmatrix}

Answer: 
\begin{bmatrix}
16 & 26 \\
19 & 31
\end{bmatrix}




Question: Given 2 numpy arrays as matrices, output the result of Dot the 2 matrices

\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}

\begin{bmatrix}
2 & 3 & 4 \\
5 & 6 & 7 \\
8 & 9 & 10
\end{bmatrix}


In [20]:
arr_1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr_2 = np.array([[2,3,4], [5,6,7], [8,9,10]])
print(arr_1.dot(arr_2))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


construct a 2X3 random matrix and transpose it

In [21]:
original_mat = np.random.randint(1,20,(2,3))
print(f"original matrix:\n{original_mat}")

transpose = original_mat.T
print(f"\ntranspose:\n{transpose}")

original matrix:
[[ 3  3  2]
 [ 9 15 18]]

transpose:
[[ 3  9]
 [ 3 15]
 [ 2 18]]


numpy.std(arr, axis = None) : Compute the standard deviation of the given data (array elements) along the specified axis(if any)

Standard Deviation (SD) is measured as the spread of data distribution in the given data set.


calculate standard deviation of following matrix.
\begin{bmatrix}
2 & 2 & 2 & 2 & 2 \\
15 & 6 & 27 & 8 & 2 \\
23 & 2 & 54 & 1 & 2 \\
11 & 44 & 34 & 7 & 2
\end{bmatrix}

In [22]:
# calculate std for flatten (whole std)

A = np.array([[2,2,2,2,2], [15,6,27,8,2], [23,2,54,1,2], [11,44,34,7,2]])
np.std(A)

np.float64(15.3668474320532)

In [23]:
# calculate std along axis 0 and 1 also

print(np.std(A, axis=1))
print(np.std(A, axis = 0))

[ 0.          8.7772433  20.53874388 16.40243884]
[ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]


### use case of inverse matrix:

- The inverse of a matrix is that matrix which when multiplied with the original matrix will give an identity matrix. 

- The inverse of a matrix exists only if the matrix is non-singular i.e., the determinant should not be 0. 

**Formula**

if det(A) != 0
    A-1 = adj(A)/det(A)
else
    "Inverse doesn't exist"
    
Usage: to solve equation like this:


Where:

A-1: The inverse of matrix A

x: The unknown variable column

B: The solution matrix



Inverse the following matrix 
\[
\begin{bmatrix}
6 & 1 & 1 \\
4 & -2 & 5 \\
2 & 8 & 7
\end{bmatrix}


In [24]:
A = np.array([[6,1,3],[4,-2,5], [2,8,7]])
print(f"A:\n{A}")
inv_A = np.linalg.inv(A)
print(f"\nInverse fo A:\n{inv_A}")

A:
[[ 6  1  3]
 [ 4 -2  5]
 [ 2  8  7]]

Inverse fo A:
[[ 0.23076923 -0.07264957 -0.04700855]
 [ 0.07692308 -0.15384615  0.07692308]
 [-0.15384615  0.1965812   0.06837607]]


Load an Image using PIL and convert to numpy array.


In [25]:
! pip install pillow

In [26]:
from PIL import Image
image = Image.open(r"D:\AI learning\numpy\anything.jpg")
image_array = np.array(image)

print(image_array)
print("Shape:", image_array.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
Shape: (571, 800, 3)


convert dictionary {0: 0, 1: 1, 2: 8, 3: 27,
                4: 64, 5: 125, 6: 216}
to array

In [27]:
data = {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216}
arr = np.array(list(data.values()))
print(arr)

[  0   1   8  27  64 125 216]


Solve the Following Equation



In [28]:
import numpy as np
a = np.array([[3,1,-1], [2,-1,1], [1,2,3]])
b = np.array([9,3,12])
solutions = np.linalg.solve(a,b)
print("Solution:", solutions)

Solution: [2.4 3.  1.2]


Write a NumPy program to create a 3x3x3 array with random values and flatten it to a 1D array.


In [29]:
a = np.random.random((3,3,3))
print(a)
print(a.reshape(-1))

[[[0.32851851 0.36207172 0.32578804]
  [0.41669802 0.40474787 0.04315677]
  [0.94334051 0.74270286 0.24399568]]

 [[0.66421605 0.39236544 0.27152966]
  [0.12568014 0.48430386 0.47341566]
  [0.33541064 0.28046841 0.29678459]]

 [[0.09262634 0.10160538 0.6105381 ]
  [0.81257862 0.06685963 0.08511059]
  [0.69798438 0.19675073 0.60874229]]]
[0.32851851 0.36207172 0.32578804 0.41669802 0.40474787 0.04315677
 0.94334051 0.74270286 0.24399568 0.66421605 0.39236544 0.27152966
 0.12568014 0.48430386 0.47341566 0.33541064 0.28046841 0.29678459
 0.09262634 0.10160538 0.6105381  0.81257862 0.06685963 0.08511059
 0.69798438 0.19675073 0.60874229]


Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.

In [30]:
array = np.random.random((3,3))
print("Original array:", "\n", array)

Original array: 
 [[0.56503688 0.98799072 0.30752087]
 [0.07233901 0.40275674 0.16778089]
 [0.57223341 0.42274326 0.53452977]]


In [31]:
# Pairwise Euclidean distance

eud_dist = np.linalg.norm(array[:, np.newaxis] - array, axis=2)
print("Pairwise Euclidean distance:\n", eud_dist)

Pairwise Euclidean distance:
 [[0.         0.77767426 0.60917117]
 [0.77767426 0.         0.62032137]
 [0.60917117 0.62032137 0.        ]]
